---
# file: tasks/main.yml

- name: "Install Zabbix agent if desired"
  include_tasks: "install/{{ ansible_distribution }}.yml"

- name: "Install User Parameters"
  template:
    src: "{{ macklus.zabbix.agent.version }}/{{ item }}.j2"
    dest: "/etc/zabbix/zabbix_agentd.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ macklus.zabbix.agent.userparameters }}"
  when: macklus.zabbix.agent.userparameters is defined
  notify: restart-zabbix-agent
